[platformio]
default_envs = lilygo-t-display

[env:lilygo-t-display]
platform = espressif32
board = lilygo-t-display
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

upload_speed = 115200

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor