[platformio]
default_envs = lilygo-t-display

[env:lilygo-t-display]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor settings used by GuardianTone
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Fast upload speed supported by most ESP32 boards.
; If uploading is unreliable, lower this to 115200.
upload_speed = 921600
